//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginScratch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class log_in
    {
        public int UserId { get; set; }
        //[Required]
        //[EmailAddress]
        //[StringLength(150)]
        public string email { get; set; }
        //[Required]
        //[DataType(DataType.Password)]
        //[StringLength(20, MinimumLength = 6)]
        public string pass { get; set; }
        public string passsalt { get; set; }
    }
}
